### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by chuanyou-tang** [PredixDev/predix-seed#62]
trying to run the new seed app in the devbox (3.4.5-i) but got following error:

```
[predix@localhost predix-seed]$ node --version
v0.10.35
[predix@localhost predix-seed]$ gulp

/predix/git_projects/predix-seed/gulpfile.js:2
const gulp = require('gulp');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)

```

**Comment by gstroup** [comment]
Thanks for raising this issue.  Can you please try to update node to the latest LTS version?  Then you'll need to reinstall the predix-seed modules using `npm install` again.  I think we probably need to update the package.json file for this project, and also update the node version on the dev box.  Thank you.

**Comment by mdwragg** [comment]
Hi, I'll close this as it looks like an old version of node is used in "dev box" (not exactly sure what that is?). Can you report this issue to whoever maintains dev box please? Thanks!

p.s. `const` has had support for quite a while in node: http://kangax.github.io/compat-table/es6/

**Comment by turnerth** [comment]
no need.  Dev Box has been upgraded to the latest version of node.
[predix@predix-devbox ext-interface]$ node -v
v6.3.0

**Comment by mdwragg** [comment]
Cool. Thanks for confirming @turnerth
